/**
 * 文件名称：enums.ts
 * 文件作用：领域枚举定义，集中维护需求、子目标、执行、决策、工作器和事件的状态常量。
 *
 * 主要职责：
 * 1. 定义核心状态机使用的所有枚举值。
 * 2. 为事件调度、仓储校验和接口响应提供统一字面量来源。
 * 3. 降低跨模块硬编码状态字符串的风险。
 *
 * 依赖模块：
 * - 无外部业务依赖。
 *
 * 注意事项：
 * - 修改枚举值会影响数据文件、事件处理器和前端展示，需要谨慎迁移。
 * - 新增事件类型时，应同步补充事件载荷类型与校验规则。
 */
export enum DemandState {
  PENDING_ALIGNMENT = "PENDING_ALIGNMENT",
  READY = "READY",
  ACTIVE = "ACTIVE",
  PENDING_DECISION = "PENDING_DECISION",
  PAUSED = "PAUSED",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED"
}

export enum DemandPhase {
  ALIGNMENT = "ALIGNMENT",
  PLANNING = "PLANNING",
  EXECUTION = "EXECUTION",
  REVIEW = "REVIEW",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED"
}

export enum SubgoalState {
  PLANNED = "PLANNED",
  READY = "READY",
  DISPATCHED = "DISPATCHED",
  EXECUTING = "EXECUTING",
  BLOCKED = "BLOCKED",
  VERIFYING = "VERIFYING",
  DONE = "DONE",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED"
}

export enum ExecutionState {
  QUEUED = "QUEUED",
  RUNNING = "RUNNING",
  WAITING_RESULT = "WAITING_RESULT",
  VERIFYING = "VERIFYING",
  DONE = "DONE",
  FAILED = "FAILED",
  INTERRUPTED = "INTERRUPTED",
  TIMEOUT = "TIMEOUT",
  CANCELLED = "CANCELLED"
}

export enum DecisionStatus {
  OPEN = "OPEN",
  RESOLVED = "RESOLVED",
  EXPIRED = "EXPIRED",
  CANCELLED = "CANCELLED"
}

export enum WorkerRegistryStatus {
  IDLE = "idle",
  BUSY = "busy",
  OFFLINE = "offline",
  ERROR = "error",
  DISABLED = "disabled"
}

export enum WorkerExecutionStatus {
  IDLE = "idle",
  RUNNING = "running",
  BLOCKED = "blocked",
  OFFLINE = "offline",
  ERROR = "error"
}

export enum WorkerResultStatus {
  DONE = "DONE",
  BLOCKED = "BLOCKED",
  FAILED = "FAILED",
  NEED_HELP = "NEED_HELP",
  PARTIAL = "PARTIAL"
}

export enum VerificationStatus {
  VERIFIED_DONE = "VERIFIED_DONE",
  PARTIAL = "PARTIAL",
  FAILED = "FAILED",
  UNVERIFIABLE = "UNVERIFIABLE"
}

export enum DecisionReasonCode {
  MISSING_INFO = "MISSING_INFO",
  MISSING_PERMISSION = "MISSING_PERMISSION",
  INSTALL_REQUIRES_REVIEW = "INSTALL_REQUIRES_REVIEW",
  PLAN_CONFLICT = "PLAN_CONFLICT",
  PLAN_REVIEW = "PLAN_REVIEW",
  PATH_GRANT_REQUIRED = "PATH_GRANT_REQUIRED",
  UNVERIFIABLE_RESULT = "UNVERIFIABLE_RESULT",
  HIGH_RISK_ACTION = "HIGH_RISK_ACTION",
  BLOCKED = "BLOCKED",
  OPS_ALERT = "OPS_ALERT"
}

export enum DecisionAction {
  APPROVE = "Approve",
  REJECT = "Reject",
  PROVIDE_INFO = "ProvideInfo",
  PAUSE = "Pause",
  STOP = "Stop",
  CANCEL_DEMAND = "CancelDemand"
}

export enum EventType {
  USER_INPUT_RECEIVED = "USER_INPUT_RECEIVED",
  DEMAND_CREATED = "DEMAND_CREATED",
  DEMAND_CLARIFICATION_COMPLETED = "DEMAND_CLARIFICATION_COMPLETED",
  PLAN_GENERATED = "PLAN_GENERATED",
  SUBGOAL_CREATED = "SUBGOAL_CREATED",
  SUBGOAL_MARKED_READY = "SUBGOAL_MARKED_READY",
  EXECUTION_CREATED = "EXECUTION_CREATED",
  EXECUTION_DISPATCHED = "EXECUTION_DISPATCHED",
  WORKER_HEARTBEAT_RECEIVED = "WORKER_HEARTBEAT_RECEIVED",
  WORKER_RESULT_RECEIVED = "WORKER_RESULT_RECEIVED",
  VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED",
  RECONCILIATION_COMPLETED = "RECONCILIATION_COMPLETED",
  SUBGOAL_RETRY_REQUESTED = "SUBGOAL_RETRY_REQUESTED",
  DECISION_REQUEST_CREATED = "DECISION_REQUEST_CREATED",
  DECISION_RESPONSE_RECEIVED = "DECISION_RESPONSE_RECEIVED",
  REPLAN_REQUESTED = "REPLAN_REQUESTED",
  DEMAND_PAUSED = "DEMAND_PAUSED",
  DEMAND_RESUMED = "DEMAND_RESUMED",
  DEMAND_CANCELLED = "DEMAND_CANCELLED",
  EXECUTION_STOP_REQUESTED = "EXECUTION_STOP_REQUESTED",
  EXECUTION_TIMEOUT_DETECTED = "EXECUTION_TIMEOUT_DETECTED",
  WORKER_HEALTH_CHECKED = "WORKER_HEALTH_CHECKED",
  OPS_RECOVERY_ATTEMPTED = "OPS_RECOVERY_ATTEMPTED",
  OPS_RECOVERY_FAILED = "OPS_RECOVERY_FAILED",
  OPS_ALERT = "OPS_ALERT",
  HANDLER_FAILED = "HANDLER_FAILED",
  MISSION_COMPLETED = "MISSION_COMPLETED"
}
